### ISSUE TITLE
opam-user-setup and emacs starter kits

### ISSUE THREAD

**Issue by edwintorok** [OCamlPro/opam-user-setup#10]
Related to: https://github.com/OCamlPro/opam-user-setup/issues/6.

`opam-user-setup` should check for the presence of an `~/.emacs.d`, not just `~/.emacs` when creating its default template, and treat the presence of an .emacs.d the same as the presence of an initial .emacs file: just add the utop/merlin/ocp-indent plugins and not the whole .emacs file.
(and add that customization to .emacs.d).

Some Emacs "starter kits" only have an `.emacs.d` and no `.emacs` file. If opam-user-setup is used with these then it essentialy disables the whole starter kit leaving just the opam-user-setup generated template.

Of course one could also just add/improve OCaml support to these starter kits, which is what I tried to do with Spacemacs: https://github.com/syl20bnr/spacemacs/pull/1241.
Now it is only a matter of adding one line to your `.spacemacs` (well 3 if you want auto-complete and flycheck) to get ocaml enabled. 

I'm not sure whether opam-user-setup should support the starter kits directly, there are so many of them.
Perhaps the simplest solution for now would be to not make any modifications to .emacs.d if `.emacs.d` exists but `.emacs` doesn't, and print a warning instead.

```diff
--- /home/edwin/.emacs.d/core/templates/.spacemacs.template	2015-04-17 19:11:32.435456432 +0300
+++ /home/edwin/.spacemacs 2015-04-18 21:36:02.453924578 +0300
@@ -1,45 +1,46 @@
 ;; -*- mode: dotspacemacs -*-
 ;; This file is loaded by Spacemacs at startup.
 ;; It must be stored in your home directory.
 
 (defun dotspacemacs/layers ()
   "Configuration Layers declaration."
   (setq-default
    ;; List of additional paths where to look for configuration layers.
    ;; Paths must have a trailing slash (ie. `~/.mycontribs/')
    dotspacemacs-configuration-layer-path '()
    ;; List of configuration layers to load. If it is the symbol `all' instead
    ;; of a list then all discovered layers will be installed.
    dotspacemacs-configuration-layers
    '(
      ;; --------------------------------------------------------
      ;; Example of useful layers you may want to use right away
      ;; Uncomment a layer name and press C-c C-c to install it
      ;; --------------------------------------------------------
-     ;; auto-completion
+     auto-completion
      ;; better-defaults
      ;; (git :variables
      ;;      git-gutter-use-fringe t)
      ;; markdown
+     ocaml
      ;; org
-     ;; syntax-checking
+     syntax-checking
      )
```

**Comment by AltGr** [comment]
This should now be fixed: if there is no `~/.emacs` but a `~/.emacs.d/init.el`, that one will be used instead, which should avoid breaking the starter kits. I haven't implemented the improvement in #6, though, although the framework would fully support it.
