### ISSUE TITLE
Fails if ~/.emacs.d doesn't exist

### ISSUE THREAD

**Issue by reynir** [OCamlPro/opam-user-setup#19]
ocamltop > base > .ocamlinit: adding configuration
    emacs > /home/rbj/.emacs: installing new config file template
    emacs > base > .emacs: adding configuration
    emacs > base > .emacs.d/opam-user-setup.el: adding configuration
    emacs > ocp-indent > .emacs.d/opam-user-setup.el: adding configuration
    opam-user-setup: internal error, uncaught exception:
                     Sys_error("/home/rbj/.emacs.d/opam-user-setup.el: No such file or directory")

The vim files weren't updated. Note that I don't have emacs installed.

**Comment by AltGr** [comment]
This should be fixed already by 591ad14b6085a3c31401d31cc2aa6178ead630ed ; I'll release shortly
