### ISSUE TITLE
Bad interaction between merlin and ocp-index in emacs.

### ISSUE THREAD

**Issue by Drup** [OCamlPro/opam-user-setup#9]
Both should not be enabled together, as they predate the same key bindings in emacs ...
At the moment, ocp-index seems to get the upper hand and break merlin's C-c C-t.

Not sure how that should be solved, but it's very frustrating when you don't answer the issue and merlin can't give you the type of stuff in your file...

**Comment by AltGr** [comment]
Hm, annoying indeed. How does emacs resolve those conflicts ? Maybe loading merlin latest would be enough to give it the upper hand -- having both is valuable, I won't be giving up on `C-c /` to grep-uses-of through ocp-index+ocp-grep.

**Comment by AltGr** [comment]
If so it's just a matter of changing the order [here](https://github.com/OCamlPro/opam-user-setup/blob/aa512a8d1e2598f7c045aaeeae414bd5cce9f521/emacs/emacs.ml#L283-L288)

**Comment by AltGr** [comment]
Ah, found the issue: ocp-index passes `t` to the argument `APPEND` of `add-hook`; the default is to prepend, so merlin always ended up before.

**Comment by AltGr** [comment]
err ignore me, actually both do; the order of loading is determined by the output of `opam list`, hence alphabetic.
